---
# ShoppingList Application Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: shoppinglist
  labels:
    app: shoppinglist
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shoppinglist
  template:
    metadata:
      labels:
        app: shoppinglist
    spec:
      containers:
      - name: shoppinglist
        image: mustaqshaik123/shoppinglist:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080 # All endpoints (app, Swagger, H2) run on this port
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 20
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 60
          periodSeconds: 15
---
# ShoppingList Service (LoadBalancer for external access)
apiVersion: v1
kind: Service
metadata:
  name: shoppinglist-service
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: shoppinglist
