---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: shoppinglist
  labels:
    app: shoppinglist
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shoppinglist
  template:
    metadata:
      labels:
        app: shoppinglist
    spec:
      containers:
      - name: shoppinglist
        image: mustaqshaik123/shoppinglist:latest
        ports:
        - containerPort: 8080 # Spring Boot main port
        - containerPort: 9080 # Swagger / H2 console if exposed
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 20
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 60
          periodSeconds: 15
---
apiVersion: v1
kind: Service
metadata:
  name: shoppinglist-service
spec:
  type: LoadBalancer
  ports:
  - name: http
    port: 80
    targetPort: 8080
  - name: swagger
    port: 90
    targetPort: 9080
  selector:
    app: shoppinglist
