apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: shoppinglist-servicemonitor
  namespace: monitoring
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app: shoppinglist
  namespaceSelector:
    matchNames:
      - default
  endpoints:
    - port: http
      path: /actuator/prometheus
      interval: 15s
